runtime: nodejs22
service: default

env_variables:
  VITE_API_BASE_URL: "http://localhost:5000"
  NODE_ENV: "production"

automatic_scaling:
  max_instances: 1
  min_idle_instances: 0
  min_pending_latency: 30ms
  max_pending_latency: automatic

handlers:
  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  - url: /
    static_dir: dist

  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)